---
title: "Consumo energético final por sector en Uruguay, 1965-2016"
author: "Martínez Matías, Zang Bruno"
date: "17 de mayo de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Introducción:

El presente estudio surge de la curiosidad por conocer el comportamiento de la energía en Uruguay y posee como objetivo madre una profunda aplicación de los conocimientos adquiridos en la asignatura "Nuevas técnicas para el análisis de datos", marcando énfasis en un correcto análisis exploratorio y la generación de adecuadas visualizaciones de los datos.
Se analizará  el consumo final uruguayo de energía por sector para el período 1965-2016.


El consumo final energético representa la energía, primaria o secundaria, utilizada directamente por los sectores socioeconómicos, sin incluir el consumo final no energético. La información se presenta desagregada por sector socioeconómico con la siguiente apertura:

- Residencial
- Comercial, Servicios, Sector público
- Transporte
- Industrial
- Agro, Pesca, Minería.

## Antecedentes

En su programa del Balance Energético Nacional, donde don extrajo los datos, la Dirección Nacional de Energía del MIEM genera anualmente un suntuoso informe sobre la realidad energética en Uruguay para dicho año. Podemos observar el correspiende al 2016 tras el siguiente link: http://www.ben.miem.gub.uy/descargas/1balance/Informe%20general.pdf.

## Datos obtenidos
Los datos fueron obtenidos del Balance Energético Nacional (BEN) correspondiente al año 2016, programa que yace de la Dirección Nacional de Energía del Ministerio de Industria, Energía y Minería. 
Mediante el catálogo de datos abiertos se extrae la base de datos a utilizar, desde el siguiente url: https://catalogodatos.gub.uy/it/dataset/consumo-final-energetico-por-sector.

## Descripción de las variables:

- **a:** Año 
- **res:** Residencial
- **c.s.sp:** Comercial/Servicios/Sector público
- **tran:** Transporte
- **ind :** Industrial
- **a.p.m:** Agro/Pesca/Minería
- **ni:** No identificado
- **total:** Total

La energía esta medida en unidades **ktep**,la cuál corresponde a la energía que rinde una tonelada de petróleo, la cual, como varía según la composición química de éste, se ha tomado un valor convencional de: 41.868.000.000 J (julios)  o 11.630 kWh (kilovatios-hora). 

## Modelos y herramientas:

Es importarte recordar los objetivos del estudio, uno de ellos guía a la implementación de apropiadas visualizaciones. Para esto se utilizará el software estadístico R, con la puntual aplicación de paquete "tidyverse", que proporciona un conjunto de librerías óptimas para el análisis exploratorio de datos.
Con el fin de crear visualizaciónes oportunas se gestará su formación con la librería "ggplot2", perteneciente a tidyverse, la cual al trabajar mediante acumulación de capas (layers) posee una mayor flexibilidad y permite generar gráficos que representen correctamente los datos, sin generar interpretaciones confusas. Toma como referencia una metodología de visualización de datos llamada the Grammar of Graphics,
(Wilkinson, 2005), que consiste en especificar de manera independiente las componentes del gráfico, como si fuesen
bloques y luego combinarlas.

## Preguntas a responder

- 
- 
- 
- 
